### ISSUE TITLE
不是很明白 这个支持windows吗

### ISSUE THREAD

**Issue by 54huige** [tealang/tea#2]

**Comment by cmmer** [comment]
我试了一下，Windows 10 php-7.3 可以跑。

; 命令
git clone https://github.com/tealang/tea.git
cd tea
; 编译docs目录
c:\php\php.exe bin\tea docs

; 编译到了 dist/docs 文件夹

**Comment by bennycolor** [comment]
支持Windows，所支持的系统和版本依赖于PHP7.3。Tea语言编译器使用PHP7.3实现，编译生成的目标代码支持PHP7.2+。

**Comment by tealang** [comment]
支持Windows，所支持的系统和版本依赖于PHP7.3。Tea语言编译器使用PHP7.3实现，编译生成的目标代码支持PHP7.2+。
