### ISSUE TITLE
文档啊大哥，我连怎么把它编译成php都不知道

### ISSUE THREAD

**Issue by gs412** [tealang/tea#4]
php tea/bin/tea tea/docs/

这个命令行什么意思？生成文档吗？

大侠别光忙着写程序啊，文档也很重要啊，不然这么好的东西石沉大海，太可惜了

**Comment by gs412** [comment]
摸索出来了

php tea/bin/tea --init myproject/hello
php tea/bin/tea myproject/hello
php myproject/dist/hello/main.php

**Comment by tealang** [comment]
不好意思，文档比较欠缺，辛苦你摸索了😄
多谢建议，我们加把劲，后续争取把文档写完善一些。

**Comment by alfred-yan** [comment]
静态类型版的PHP？

**Comment by tealang** [comment]
> 静态类型版的PHP？

静态类型只是Tea语言的其中一个主要特性，Tea语言语法和PHP是不同的。

**Comment by gs412** [comment]
> 
> 
> 静态类型版的PHP？

最大的价值是美化，PHP本身太丑陋了，语法丑陋，函数命名混乱，历史包袱太重。PHP后面的版本也越来越重视静态类型，PHP7.4基本上可以当做静态类型语言来写了。但是语法不敢改的，因为要向前兼容。

PHP是个好语言，一直以来我都是捏着鼻子写PHP，实在太丑了。Tea语言很好的解决了这个问题，以后不用再捏着鼻子写后端了。

**Comment by tealang** [comment]
> > 静态类型版的PHP？
> 
> 最大的价值是美化，PHP本身太丑陋了，语法丑陋，函数命名混乱，历史包袱太重。PHP后面的版本也越来越重视静态类型，PHP7.4基本上可以当做静态类型语言来写了。但是语法不敢改的，因为要向前兼容。
> 
> PHP是个好语言，一直以来我都是捏着鼻子写PHP，实在太丑了。Tea语言很好的解决了这个问题，以后不用再捏着鼻子写后端了。

多谢支持，欢迎多提宝贵意见！
