### ISSUE TITLE
一直在关注，加油！

### ISSUE THREAD

**Issue by gs412** [tealang/tea#9]
刚刚看到又有更新了。php还是有很多优势的，在脚本语言里执行速度名列前茅，不需要编译即可执行，不用启动server，更新文件后立马即可见到效果，唯一的缺点就是语法太丑了，tealang刚好补足了这个短板。

**Comment by tealang** [comment]
多谢期待！
在经历了早期工作后，发现做一门编程语言的确是非常不容易的事情。现在各种编程语言已经非常成熟，新的编程语言靠单纯的语法优势很难吸引到使用者。
因此，在初次发布后，我们也在考虑如何做才真正具有价值，目前已经形成了一些新的想法，将会尽快体现出来。

**Comment by tealang** [comment]
多谢期待！
在经历了早期工作后，发现做一门编程语言的确是非常不容易的事情。现在各种编程语言已经非常成熟，新的编程语言靠单纯的语法优势很难吸引到使用者。
因此，在初次发布后，我们也在考虑如何做才真正具有价值，目前已经形成了一些新的想法，将会尽快体现出来。
